generated: '2026-07-25'
method: probed
source: live DNS/TLS/HTTP probes of apis.yml + OpenAPI hosts
hosts:
- host: www.intactfc.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Nov 27 23:59:59 2026 GMT
  hsts: null
- host: www.intact.ca
  https: true
  tls_version: TLSv1.3
  cert_expires: Oct 22 23:59:59 2026 GMT
  hsts: null
- host: www.intactspecialty.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Dec  4 23:59:59 2026 GMT
  hsts: false
domains:
- domain: intactfc.com
  dnssec: true
  caa:
  - 0 issuewild "ssl.com"
  - 0 issuewild "entrust.net"
  - 0 issue "letsencrypt.org"
  - 0 issuewild "digicert.com"
  - 0 issue "digicert.com"
  - 0 issuewild "letsencrypt.org"
  spf: true
  dmarc: true
  dmarc_policy: reject
- domain: intact.ca
  dnssec: true
  caa:
  - 0 issue "digicert.com"
  - 0 issuewild "sectigo.com"
  - 0 issuewild "ssl.com"
  - 0 issuewild "entrust.net"
  - 0 issuewild "letsencrypt.org"
  - 0 issuewild "amazon.com"
  spf: true
  dmarc: true
  dmarc_policy: reject
